### ISSUE TITLE
Missing wheels for linux and osx

### ISSUE THREAD

**Issue by boothby** [Penlect/rectangle-packer#9]
I'd like to use `rectangle-packer` as a dependency for [minorminer](https://github.com/dwavesystems/minorminer) and we generally don't require our users to have compilers for supported systems (py3.5-3.8, win / osx / linux).  I'd be happy to help building wheels for these systems, if you're interested.  Otherwise, I'll need to figure something out involving submodules (very grateful for your MIT-licensed code!)

**Comment by Penlect** [comment]
Hi @boothby , I'm happy you find the package useful. Thank you for the suggestion. Unfortunately, I've no osx machine, which is why no wheels were created. For Linux, I simply failed to wrap my head around the manylinux wheel format. However, I just now tried the cibuildwheel project which successfully built wheels for all platforms. [They are uploaded to PyPI now](https://pypi.org/project/rectangle-packer/#files). When you have time, I'd be glad to hear from you if the wheels you need work fine.

**Comment by boothby** [comment]
Thank you!  That works great!
